print(132+45)
print(125/5*2)
print(3**2*3/2)
print("Hello " + "World")
print((3+5)-(17-9)/(3*2))
print("Justin Neubauer")
print("Here " + "is " + "another " + "python " + "tutorial" + "!!!")
print("Hello " * 5)
print("Hello" + str(5))
